### ISSUE TITLE
Unable to get book name, please change another url and try again

### ISSUE THREAD

**Issue by lowi** [chenditc/safari-download#1]
I got this error while trying to download a book.

**Comment by chenditc** [comment]
What's the url you were browsing? It parse your current tab's url and see what book it is.

**Comment by lowi** [comment]
@chenditc Should have put the URL directly in the issue:
http://my.safaribooksonline.com/9781783987627/ch01_html?percentage=0&reader=html

**Comment by chenditc** [comment]
That looks like a old version of Safari, how did you end up in this page? Do you click some oreilly link and get here?

My extension works when I get the book from https://www.safaribooksonline.com/library/view/building-applications-on/9781491926543/toc01.html

You can use that as a workaround.

**Comment by lowi** [comment]
I have a very old account for safari where I get 5 books / month.
I don't have access to the link you suggested with that account.

Thanks for the help!
