### ISSUE TITLE
Only downloads first page?

### ISSUE THREAD

**Issue by fpoumian** [chenditc/safari-download#15]
I was under the impression that this extension should download the whole book when clicking on the "Download Book" button, but for me it is only downloading the first page (which is often the Preface). Am I doing something wrong? I'm not switching or closing tabs when it starts downloading, by the way.

**Comment by chenditc** [comment]
I refactored this extension, could you try to see if the [new version](https://chrome.google.com/webstore/detail/safari-books-download/anlpljppoinmpaedoilhjibjehpjhcob?hl=en-US&gl=US) works for you?
