### ISSUE TITLE
Can save to HTML instead of MHTML?

### ISSUE THREAD

**Issue by ruze00** [chenditc/safari-download#16]
Hi Chen Di, thanks for all the work in bringing this plugin to the public.  It is very useful.

However, I'm wondering is it possible to save as HTML instead of MHTML?  HTML is much easier to convert to other formats and view in various applications!

**Comment by chenditc** [comment]
If I just use plain html, you will see a directory for each chapter instead of a single file. Does that make your life easier?

**Comment by mmizutani** [comment]
@ruze00 If reading on the Amazon Kindle app is not a must, then you can use mhtml-compatible reader apps on Android such as MhtViewer and Microsoft Edge. I download pages using this plugin with maximum wrap width, unzip the zip files, copy the mhtml files therein to my Android tablet, and open them using MhtViewer, which works much better with mhtml files than Edge.

**Comment by ruze00** [comment]
The goal is to convert to EPUB easily.  That's the most popular format for e-reading.  Directories per chapter should be fine, since internally EPUB (and MHTML) combine folder content into a single package anyway.  It's just strange that so few tools support MHTML to convert from to EPUB... maybe there's one I haven't found yet, but otherwise using standard HTML even in folders sounds like it should work as an alternate download format.

**Comment by chenditc** [comment]
You can use this script to convert mhtml to html easily. https://github.com/chenditc/safari-books-archive/blob/master/mhtml_to_html_converter.py
