### ISSUE TITLE
Download only the first page

### ISSUE THREAD

**Issue by JonasUliana** [chenditc/safari-download#18]
After a few tries, the same case is always displayed, only the first page is downloaded.
Spidering does not index the next pages to download, it would be interesting some option for extension debugging.

**Comment by chenditc** [comment]
I refactored this extension, could you try to see if the [new version](https://chrome.google.com/webstore/detail/safari-books-download/anlpljppoinmpaedoilhjibjehpjhcob?hl=en-US&gl=US) works for you?
