### ISSUE TITLE
Can you rename or zip the downloaded files?

### ISSUE THREAD

**Issue by alexya** [chenditc/safari-download#2]
I like the plugin and it can work on my Chrome browser partially. 
As chrome browser has a feature/functionality named "This type of file can harm your computer" and prompt to you to choose 'DISCARD' or 'KEEP'. When you click 'Keep' button, it will prompt another confirm dialog which is too boring. 
I tried to download a safari online book, it has more than 100 pages. And the downloaded file  named  *.mhtml. chrome regards it as harmful and prompted to me 100+ times, it is impossible for me to click the 'KEEP' button by 100 times. 
I google and it seems that there is no way to disable this function 'This type of file can harm your computer'
Do u have any solution to resolve this issue? such as download all files in memory and then zip all of them into one zip file, or with the extension name .txt, etc.?

**Comment by chenditc** [comment]
That's wierd, this never happen to me. What OS are you using? I tested on my macbook and it didn't prompt me for download warning.

I guess that's chrome setting. No matter what file I download, it never prompt me warning..

**Comment by chenditc** [comment]
Can't reproduce.

**Comment by alexya** [comment]
I used both mac OSX (EI Capitan and windows 10/7)

**Comment by chenditc** [comment]
I think you can go to Chrome => settings => check box "Protect you and your device from dangerous sites". Then the alarm should go away.
