### ISSUE TITLE
not able to get the book title

### ISSUE THREAD

**Issue by wenliangz** [chenditc/safari-download#21]
This is error message" I'm not able to get the book title, please check if you have logged in. If you are sure you have logged in, please report this incidence to: https://github.com/chenditc/safari-download/issues"

**Comment by chenditc** [comment]
Have you logged in? Could you send me a screenshot of the page that you
encountered this issue?

**Comment by wenliangz** [comment]
Hi, Di, 
 
Thank you for your prompt response!! I did logged in, but with the expired account. It did work before with expired account though. Here is the screen shot. 

Thanks.
Wen

**Comment by chenditc** [comment]
You have to login with a valid account. A valid account means you can load and read full book.

I believe safaribook online make some changes to remove support for expired account.
