### ISSUE TITLE
I'm not able to get the book title

### ISSUE THREAD

**Issue by Netlabbuilder** [chenditc/safari-download#22]
I got this issue today (Already logged in with expired account). You can check the attached file as the screen capture.

Two days ago, I could get it worked but could not find the downloaded folder. Would you please tell me where it is?

![aws book](https://user-images.githubusercontent.com/31883280/37949551-7b39680a-3195-11e8-87ae-0e75ae608227.png)

**Comment by chenditc** [comment]
You have to login with a valid account. A valid account means you can load and read full book.
