### ISSUE TITLE
Could you please auto-number the files from 000 to nnn?

### ISSUE THREAD

**Issue by schittli** [chenditc/safari-download#23]
Good evening
Thank you very much for sharing this great Plugin!, it's really very useful to work with the Files offline.

Downloading some books (for example this: https://www.safaribooksonline.com/library/view/learning-powershell-dsc/9781787287242/#toc) creates GUID-Filenames like this:
```
027e61ed-56b3-4e7e-ba85-ce7e7cb5aa86.mhtml
04f8f34c-5fc3-40d8-99a4-fcccbb589211.mhtml
051d527b-4a69-46af-8b0c-9b447555bb22.mhtml
```
Because you probably know the Chapter Number:
If you sometimes update the Plugin, could you please prefix the Filenames with a chapter counter, so that we get for example:
```
000-027e61ed-56b3-4e7e-ba85-ce7e7cb5aa86.mhtml
001-04f8f34c-5fc3-40d8-99a4-fcccbb589211.mhtml
002-051d527b-4a69-46af-8b0c-9b447555bb22.mhtml
```
This would help a lot to find the right Chapter in offline mode :-)

Thanks a lot,
kind regards,
Thomas

**Comment by chenditc** [comment]
I just made this change. Please update to latest version of extension and try again.

**Comment by schittli** [comment]
**Thank you very much!,** I will try it as soon as I return from my holidays :-)

**Comment by schittli** [comment]
A friend tested it and it is much better, but if the Book has more than 9 chapters, then the display order is wrong and we have to search for the next chapters, **e.g. chapter 2 is the 23rd File in the List**:
```
ch0-titlepage.mhtml
ch10-kindle_split_009.mhtml
ch11-kindle_split_009.mhtml
…
ch18-kindle_split_018.mhtml
ch19-kindle_split_018.mhtml
ch1-kindle_split_000.mhtml
ch20-kindle_split_019.mhtml
```

If you could change it to use three characters (000 to 999 as proposed), then the problem will not appear and 3 characters should be enough for books with many chapters. Then, it will looks like this:

```
ch000-titlepage.mhtml
ch001-titlepage.mhtml
…
ch008-titlepage.mhtml
ch009-titlepage.mhtml
ch010-titlepage.mhtml
ch011-titlepage.mhtml
```

Thanks a lot for sharing and supporting this very useful tool!, 
kind regards, 
Thomas

**Comment by chenditc** [comment]
Indeed, it could be more useful if it starts from 001 instead of 1

**Comment by chenditc** [comment]
Done, please update to latest version and try again.

**Comment by schittli** [comment]
Thank you very much!, it works perfect :-)
