### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by lezwon** [chenditc/safari-download#26]
Extension gives the following error when i open the book and attempt downloading:

I'm not able to get the book title, please check if you have logged in with a *valid* account. A valid account means you can load and read the full book. If you are sure you have logged in, please report this incidence to: https://github.com/chenditc/safari-download/issues

**Comment by chenditc** [comment]
Do you have a valid account?

**Comment by lezwon** [comment]
Yes

**Comment by VictorBonasa** [comment]
Hi, same issue for me. I have logged in with a valid account and i can read the full book.

**Comment by chenditc** [comment]
Could you provide a screenshot when you are trying to download a book?
