### ISSUE TITLE
EPUB, MOBI or PDF file format support?

### ISSUE THREAD

**Issue by eyanq** [chenditc/safari-download#28]
Hi @chenditc,

Thanks for the awesome work and it's really helps me a lot! Just wondering is there any future plan for supporting other Kindle-friendly file formats, e.g. .epub, .mobi or .pdf? 

Cheers

**Comment by chenditc** [comment]
I do want to support these file format, it's currently blocked because I can't find a good api to transform mhtml file to pdf or .epub.

**Comment by TAbdiukov** [comment]
As simple as it is, the best way to convert is as follows. 

For every MHTML file do,
 1. Open it up in Chrome
 2. Ctrl+P - Save as PDF
Rinse and repeat

**Comment by chenditc** [comment]
I do have some script to turn convert mhtml to html file in https://github.com/chenditc/safari-books-archive

Then if you host the HTML file on a web server, then you can use public service to create mobi and epub file from your site. 

I don't think there is an easy way to do that in a chrome extension. So I prefer just leave the plugin as it.

**Comment by mohsinkerai** [comment]
Is there any tool that converts zip containing mhtml to epub/mobi?
