### ISSUE TITLE
change of format ?

### ISSUE THREAD

**Issue by DickBaker** [chenditc/safari-download#29]
I am getting error "I'm not able to get the book title, please check if you have logged in with a *valid* account. A valid account means you can load and read the full book. If you are sure you have logged in, please report this incidence to: https://github.com/chenditc/safari-download/issues" on [all] titles, such as https://www.safaribooksonline.com/library/view/tensorflow-machine-learning/9781789132212

I suspect that Safari have changed their underlying format to .xhtml such as this URL
https://www.safaribooksonline.com/library/view/tensorflow-machine-learning/9781789132212/5019f99e-22fc-426e-8ec9-a63030cdbb48.xhtml

BTW I am fully logged-in and able to navigate online to any page within this/other title.

Would it be possible to accommodate this strict flavour of html so that this useful extension can be brought back to life ?

thanks

**Comment by chenditc** [comment]
I tried the link you provided, and I was able to download the book. Please check if you are using the latest version of the plugin.

**Comment by chenditc** [comment]
tensorflow_machine_learning_projects.zip
<https://drive.google.com/a/umich.edu/file/d/1yZMeJu2NAvzjobD2rlFmMTt9TrzmQp9Y/view?usp=drive_web>
I tried with the latest version of the plugin, and here is the zip file it
produce.
