### ISSUE TITLE
Not working in http://techbus.safaribooksonline.com/

### ISSUE THREAD

**Issue by jhomzki** [chenditc/safari-download#3]

**Comment by chenditc** [comment]
I don't have access to http://techbus.safaribooksonline.com/, what is this site for?

**Comment by jhomzki** [comment]
This the old site for safari books online. I'm just thinking if this can be added to your code..

On Oct 22, 2016 5:36 AM, Di notifications@github.com wrote:

I don't have access to http://techbus.safaribooksonline.com/, what is this site for?

**Comment by chenditc** [comment]
Oh... ok. For now, this tool fits all my needs, so I don't realy want to dig into old site that might get retired sometime in the future.

**Comment by lawilap** [comment]
http://techbus.safaribooksonline.com/  is not an old but a subsidiary part of safaribooksonline, its mostly used by corporate employees who gets access to safaribooks via their organisation. I tried adding this to your code, but it didn't work, maybe I'm doing something wrong. Can you please guide me where can I make changes to get this extension working on techbus domain. Million thanks from all those who are waiting for your response.

**Comment by GitHubSouceCodeAdmin** [comment]
I agree with Lawilap, it would be really helpful if you could add in support for techbus.safaribooksonline.com because it's a huge part of safari. Many people, and new accounts use that. It has to do with how they provision various types of catalogs. This is one of the largest ones

**Comment by multiflexi** [comment]
proquest.safaribooksonline.com would be also nice as it is used by universities.

**Comment by gylns** [comment]
does it work for ezproxy url?

**Comment by watsoncl** [comment]
I can't seem to get the extension to work via "proquest.safaribooksonline.com"

**Comment by chenditc** [comment]
Only standard "www.safaribooksonline.com" is supported. You are welcome to fork this repo and support your own need.
