### ISSUE TITLE
Add support for URI "https://learning.orelly.com"

### ISSUE THREAD

**Issue by tribals** [chenditc/safari-download#30]
Right now O'Relly merges Safari Books with their united learning platform. They already set up redirect when visiting https://safaribooksonline.com.

**Comment by chenditc** [comment]
Indeed, they did set up a redirect. I just didn't get redirected because I was logged in into the account

**Comment by chenditc** [comment]
Latest 1.5.1 version on chrome web store has this fix

**Comment by tribals** [comment]
Thank you!
