### ISSUE TITLE
cant download any title since today 

### ISSUE THREAD

**Issue by eugsim1** [chenditc/safari-download#31]
Hi since today i cant download any title i m getting this message : I'm not able to get the book title, please check if you have logged in with a *valid* account. A valid account means you can load and read the full book. If you are sure you have logged in, please report this incidence to: https://github.com/chenditc/safari-download/issues

i can read the books content as i m logged to the site but the download button stopped to work any tips ?
Thanks

**Comment by codeban** [comment]
Dupplicate of #30 
With fixing this issue it works again.

**Comment by Prakash-Ponnusamy1** [comment]
Where do I download the updated .crx file which supports download from learning.oreilly.com ?
I couldn't find a link to download.
Any link would be really helpful.

**Comment by chenditc** [comment]
https://chrome.google.com/webstore/detail/safari-books-download/anlpljppoinmpaedoilhjibjehpjhcob?hl=en-US&gl=US

You can download latest package here
