### ISSUE TITLE
doensn't work anymore https://learning.oreilly.com/library/view/kirkpatricks-investment-and/9780132597609/ch04.html

### ISSUE THREAD

**Issue by moongraber** [chenditc/safari-download#35]
Hi

it doesn't work anymore tried 
https://learning.oreilly.com/library/view/kirkpatricks-investment-and/9780132597609/ch04.html

get error:
I'm not able to get the book title, please check if you have logged in with a *valid* account. A valid account means you can load and read the full book. If you are sure you have logged in, please report this incidence to: https://github.com/chenditc/safari-download/issues

**Comment by chenditc** [comment]
Could you provide a screenshot?

**Comment by moongraber** [comment]
HI

I tested just now with link:
https://learning.oreilly.com/library/view/mastering-options/9781631579080/

and it worked just fine!

thanks!
