### ISSUE TITLE
Same here: no more download possible; instead the message "I am not able to get the book title." 

### ISSUE THREAD

**Issue by syrom** [chenditc/safari-download#36]
Cannot download the Python Pocket Reference from
https://github.com/chenditc/safari-download/issues

Instead, the plugin says it cannot retrieve the book title and I should check if I am looged in correctly - which I am.

**Comment by chenditc** [comment]
Could you provide a screenshot?

**Comment by syrom** [comment]
Funny - seems to work now ! If I should happen to stumble across this error again, I'll make a screenshot right away and append it to the post !
BTW, thx for this awesom plugin - good to see that someone from the community assures a usability of the service that O'Reilley doesn't seem to be interested in ....

**Comment by chenditc** [comment]
Nice, glad to hear that your like this plugin.
