### ISSUE TITLE
I'm not able to get the book title, please check if you have logged in with a *valid* account.

### ISSUE THREAD

**Issue by dhavalsp** [chenditc/safari-download#37]
I am getting this issues too. We have account access from our employer. Please guide me.

**Comment by kyjak** [comment]
same issue.

**Comment by pifarik** [comment]
https://learning.oreilly.com - just go and login there

**Comment by chenditc** [comment]
Could you provide a screenshot?

**Comment by dhavalsp** [comment]
![safariissue](https://user-images.githubusercontent.com/19658195/51329028-99ae2000-1a42-11e9-91ff-251f782cb062.PNG)
 I have attached the screenshot of the error. I am logged in by employer site to access the safari. I can access all site and books to read but just not able to download.

**Comment by dhavalsp** [comment]
> https://learning.oreilly.com - just go and login there

I cannot login directly. We have to go throw the employer learning portal to access the safari.

**Comment by kyjak** [comment]
Yes, I can confirm, I'm logged in, employer OAUTH.

**Comment by chenditc** [comment]
Sorry, this plugin only works for learning.oreilly.com domain. If you are using your employer domain, you can try to clone this repo can replace all learning.oreilly.com with your employer domain and try again.

**Comment by chenditc** [comment]
Only support learning.oreilly.com domain right now.
