### ISSUE TITLE
Save files with chapter names?

### ISSUE THREAD

**Issue by markx** [chenditc/safari-download#4]

**Comment by chenditc** [comment]
Not sure if all the books are organized by chapter, but if so, we can definitely use "ch000--<actual chapter name>" as the file name. The only thing I'm concerned is the space character and some special character might cause problem on Windows OS.

**Comment by chenditc** [comment]
I refactored this extension, could you try to see if the [new version](https://chrome.google.com/webstore/detail/safari-books-download/anlpljppoinmpaedoilhjibjehpjhcob?hl=en-US&gl=US) works for you?
