### ISSUE TITLE
Include other safaribooks domains?

### ISSUE THREAD

**Issue by MaxMatti** [chenditc/safari-download#7]
My library links to an ebook on the following link:
[http://proquest.tech.safaribooksonline.de/1597490474](http://proquest.tech.safaribooksonline.de/1597490474)
(linked from [here](http://katalogbeta.slub-dresden.de/id/0003593588/#detail))

When clicking the link from the library website, the book is readable (in their weird web interface).

When trying to use the extension to download the ebook I only get the message "Unable to get book name, please change another url and try again" after clicking the icon in the top bar.

Would it be possible to add the above mentioned domain name to the extension?

**Comment by chenditc** [comment]
I don't think I would want to support such customized safari books domain. But still, you are welcome to modify and tune the code to your need.
